'use strict';

/**
 * The work listing.
 *
 * Two kinds of entry:
 *
 *   framer: true  - the four Framer CMS case studies. Their pages already exist
 *                   and are generated by gen-framer-routes.js. Listed here only
 *                   so one page shows the whole portfolio.
 *
 *   framer: false - the newer projects. Their pages are generated statically by
 *                   gen-service-pages-v2.js, because the CMS collection cannot
 *                   be added to without Framer editor access.
 *
 * `summary` for the newer projects is taken from each client's own live site -
 * their title and meta description - and `platform` from the platform markers
 * served in their HTML. Nothing about scope, duration or results appears here,
 * because none of it can be verified from outside. Those get added when the
 * detail arrives; until then the pages say what is true and stop.
 */

module.exports = [
  // ---- Framer CMS case studies (pages already exist) ----
  {
    framer: true,
    slug: 'dropx-website-design',
    title: 'DropX Website Design',
    sector: 'Digital product',
    platform: 'Framer',
    tagline: 'A sleek landing page for a digital product, built around a single conversion.',
  },
  {
    framer: true,
    slug: 'orblead-website-design',
    title: 'ORBLEAD Website Design',
    sector: 'SaaS',
    platform: 'Framer',
    tagline: 'A minimalist lead generation site for a SaaS product, built for clarity.',
  },
  {
    framer: true,
    slug: 'shine-skincare-branding',
    title: 'Shine Skincare Branding',
    sector: 'Cosmetics',
    platform: 'Brand identity',
    tagline: 'Brand identity and visual system for an independent skincare brand.',
  },
  {
    framer: true,
    slug: 'oh-my-pasta-branding',
    title: 'Oh My Pasta Branding',
    sector: 'Food and beverage',
    platform: 'Brand identity',
    tagline: 'A distinctive identity for a pasta bar, built to be recognised on a street.',
  },

  // ---- Static pages generated by gen-service-pages-v2.js ----
  {
    framer: false,
    slug: 'voice-and-data-resale',
    title: 'Voice & Data Resale',
    client: 'Voice & Data Resale',
    url: 'https://voiceanddataresale.com',
    sector: 'IT asset recovery',
    platform: 'Shopify',
    tagline: 'A Shopify store for a UK IT asset recovery and data destruction business.',
    summary:
      'Voice & Data Resale helps businesses and consumers recover value from retired technology through secure IT asset recovery, certified data destruction and refurbishment. The company states it has traded for over thirty years.',
    build: 'Shopify storefront design and build.',
  },
  {
    framer: false,
    slug: 'cyb3r-media',
    title: 'CYB3R Media',
    client: 'CYB3R Media',
    url: 'https://www.cyb3rmedia.com',
    sector: 'Marketing agency',
    platform: 'Webflow',
    tagline: 'A Webflow site for an agency selling brand, web and performance in one place.',
    summary:
      'CYB3R Media is a digital and media agency that brings brand, web design and performance marketing together under one partner rather than splitting them across suppliers.',
    build: 'Webflow site design and build.',
  },
  {
    framer: false,
    slug: 'soznikar',
    title: 'Soznikar',
    client: 'Soznikar',
    url: 'https://soznikar.com',
    sector: 'Luxury retail',
    platform: 'Shopify',
    tagline: 'A Shopify store for hand-loomed Kashmiri pashmina, sold into the Gulf.',
    summary:
      'Soznikar sells hand-loomed Kashmiri pashmina ghutras to the Gulf market. Every piece is woven and sozni-embroidered by hand, so the store had to carry detail and provenance rather than move volume.',
    build: 'Shopify storefront design and build.',
  },
  {
    framer: false,
    slug: 'storage-hire',
    title: 'Storage Hire',
    client: 'Storage Hire Ltd',
    url: 'https://storagehireltd.com',
    sector: 'Storage and logistics',
    platform: 'Wix',
    tagline: 'A Wix site for a managed storage company in Essex, built around local search.',
    summary:
      'Storage Hire offers secure managed storage in Harlow, Essex, looked after by their team rather than self-service, on weekly or monthly terms with no long contract. The site carries LocalBusiness and OfferCatalog structured data, which is what puts a local business in front of nearby search.',
    build: 'Wix site design and build.',
  },
];
